### PR TITLE
Zepto 1.0 update

### PR DESCRIPTION
**Pull request by tedtate**
So Zepto 1.0 is now upon us and I was wondering how everyone felt about updating our Zepto to match.

Tests seemed to pass without any hiccups on the platforms I tried (Chrome 27, iOS 5, Android 4.2).

@johnboxall @rrjamie @jansepar @noahadams your thoughts?

### CODE REVIEW

**Comment by jansepar** [comment]
Does Zepto fix the issue that we had with Zepto? It would be great if we could just stop maintaining our own Zepto fork... I think we forked because of some issue with Firefox Mobile. @tedtate could you investigate?

**Comment by jansepar** [comment]
cc @romanrudenko , he should be able to help determine that as well.

**Comment by tedtate** [comment]
@jansepar The changes made by @romanrudenko to fix the FF Mobile issue are still in this branch. If you make a PR from this to madrobby/zepto:master you can see them.

@romanrudenko do you know if your changes are still necessary to maintain FF Mobile compatibility? If they aren't then maybe the best course of action is to update our submodule in mobifyjs to point to madrobby/zepto.

**Comment by romanrudenko** [comment]
The only change that is needed lives at https://github.com/romanrudenko/zepto/commit/f93dfe4f49fb566b1b72267f5ff1eba57b47ab80#src/zepto.js

From what I understand, my fix is still needed, as pull request that I issued was not accepted and ternary operators are still used in a way that would get borked after FF toString conversion. What you can do is take zepto 1.0 and apply the above-linked fix.

**Comment by tedtate** [comment]
@romanrudenko Those changes are already included here so I think we should be good to go.

**Comment by tedtate** [comment]
Closing, no longer relevant

**Pull request closed without merging**
