### PR TITLE
Ensure using array's native filter()

### PR DESCRIPTION
**Pull request by vmarta**
Fixed conflict with Prototype framework. Thanks, John and Ted.

### CODE REVIEW

**Comment by rrjamie** [comment]
Can you change all the calls to Array.filter to use the saved filter function?

**Comment by vmarta** [comment]
Ryan, I've committed an update.

**Comment by vmarta** [comment]
@rrjamie Wait for a moment before merging this pull request.  Sorry, I think my latest commit is not right.

**Comment by vmarta** [comment]
I'm going to close this pull request, since my commits are messy :)  Let me make a new one.

**Pull request closed without merging**
